sudo: false
language: go
# TODO Update after https://github.com/travis-ci/gimme/issues/93 is resolved.
go: 1.8.3

branches:
  only:
  - authoring

addons:
  apt:
    packages:
     - python-pygments=2.1.3

install:
 - go get -u -v github.com/gohugoio/hugo
script:
 - hugo -v

deploy:
  fqdn: remexre.xyz
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: authoring
  provider: pages
  skip_cleanup: true
  target_branch: master
