sudo: false
language: go
# TODO Update after https://github.com/travis-ci/gimme/issues/93 is resolved.
go: 1.8.3

addons:
  apt:
    packages:
     - python-pygments==2.1.3

install:
 - go get -u -v github.com/gohugoio/hugo
 - go get -u -v github.com/santhosh-tekuri/jsonschema/cmd/jv
 - go get -u -v github.com/wjdp/htmltest
script:
 - hugo -v

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
  provider: pages
  skip_cleanup: true
