language: rust
rust: stable
# language: generic
os: linux

branches:
  only:
  - authoring

cache:
  directories:
  - $HOME/.cargo
  - $HOME/gutenberg

install_next:
- mkdir -p ~/.local/bin
- cd ~/.local/bin
- curl -L https://github.com/Keats/gutenberg/releases/download/v0.4.2/gutenberg-v0.4.2-x86_64-unknown-linux-gnu.tar.gz | tar xz
- export PATH=$HOME/.local/bin:$PATH
- cd $TRAVIS_BUILD_DIR

install:
  - test -d $HOME/gutenberg/.git || git clone https://github.com/remexre/gutenberg.git $HOME/gutenberg --branch feature/runtime-syntax-loading
  - cargo install --force --path $HOME/gutenberg

script:
- gutenberg build --base-url https://remexre.xyz/

deploy:
  fqdn: remexre.xyz
  github_token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: authoring
  provider: pages
  skip-cleanup: true
  target-branch: master
