language: minimal
os: linux

branches:
  only:
  - authoring

install:
  - mkdir -p ~/.local/bin
  - curl -L https://github.com/getzola/zola/releases/download/v0.5.0/zola-v0.5.0-x86_64-unknown-linux-gnu.tar.gz | tar zxC ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH

script:
- zola build --base-url https://remexre.xyz/

deploy:
  fqdn: remexre.xyz
  github_token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: authoring
  provider: pages
  skip-cleanup: true
  target-branch: master
