title: remexre.xyz
email: remexre@gmail.com
description: >
  Something that's quite like a blog, except for the part where it's not useful
  or interesting. Basically, something more permanent than a spiral notebook.
baseurl: ""
url: "https://remexre.xyz"
github_username:  remexre

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
