base_url = "https://remexre.xyz/"

title = "remexre.xyz"
description = "remexre.xyz"
language_code = "en"

highlight_code = true
highlight_theme = "material-dark"

generate_rss = true
rss_limit = 100

generate_tags_pages = true
generate_categories_pages = true

compile_sass = false
