base_url = "https://remexre.xyz"

title = "remexre.xyz"

highlight_code = true
highlight_theme = "monokai"

generate_rss = true
hard_link_static = true

compile_sass = false
build_search_index = true
