base_url = "https://remexre.xyz/"
title = "remexre.xyz"
highlight_code = true
highlight_theme = "monokai"

generate_rss = true
compile_sass = false

[external_highlighters]
dot = "echo -n '<p>'; dot -Tsvg | tail -n +4; echo '</p>'"

[[taxonomies]]
name = "categories"
rss = true

[[taxonomies]]
name = "tags"
rss = true
