name: Build
on:
  push:
    branches:
    - authoring
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Zola
      run: curl -LO https://github.com/remexre/zola/releases/download/remexre-fork-pr-883/zola
    - name: chmod Zola
      run: chmod +x zola
    - name: Run Zola
      run: ./zola build
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: authoring
        BRANCH: master
        FOLDER: public
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
